name: Deploy React App

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # 👈 IMPORTANT

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20   # your app runtime (can also use 18/20)

      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Build
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

      - name: Deploy
        uses: actions/deploy-pages@v4